//using System.Diagnostics;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PlayerPicking : MonoBehaviour
{
    public float interactionDistance = 2f;
    private Transform heldItem;
    private Collider[] originalColliders; // Dodano pole do przechowywania pierwotnych collider雕 trzymanego obiektu

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.E))
        {
            Collider[] colliders = Physics.OverlapSphere(transform.position, interactionDistance);
            Transform nearestObject = null;
            foreach (Collider collider in colliders)
            {
                if (collider.CompareTag("Item"))
                {
                    if (heldItem == collider.transform)
                    {
                        continue;
                    }

                    if (nearestObject == null)
                    {
                        nearestObject = collider.transform;
                        continue;
                    }

                    if (Vector3.Distance(transform.position, nearestObject.position) > Vector3.Distance(transform.position, collider.transform.position))
                    {
                        nearestObject = collider.transform;
                    }
                }
            }

            if (nearestObject != null)
            {
                if (heldItem != null)
                {
                    // Przywracanie collider雕, gdy trzymany obiekt jest odk쓰dany
                    EnableColliders(heldItem.gameObject);
                    DropItem();
                }

                PickUpItem(nearestObject);
                // Wy씿czanie collider雕 po podniesieniu nowego obiektu
                DisableColliders(nearestObject.gameObject);
            }
        }

        if (Input.GetKeyDown(KeyCode.R) && heldItem != null)
        {
            // Przywracanie collider雕 przedmiotu przed odk쓰daniem
            EnableColliders(heldItem.gameObject);
            DropItem();
        }
    }

    void PickUpItem(Transform item)
    {
        heldItem = item;
        Debug.Log("Podnoszenie przedmiotu: " + heldItem.name);

        // Przechowaj pierwotne collidery trzymanego obiektu
        originalColliders = heldItem.GetComponentsInChildren<Collider>();

        // Wy씿cz collidery trzymanego obiektu
        foreach (Collider collider in originalColliders)
        {
            collider.enabled = false;
        }

        heldItem.parent = transform;
        heldItem.localPosition = Vector3.zero;
        heldItem.localRotation = Quaternion.identity;
    }

    void DropItem()
    {
        Debug.Log("Odk쓰danie przedmiotu: " + heldItem.name);

        // Odk쓰damy przedmiot
        heldItem.parent = null;

        // Przywracanie collider雕 trzymanego obiektu
        EnableColliders(heldItem.gameObject);

        // Przeniesienie obiektu do sceny
        MoveObjectToScene(heldItem.gameObject);

        heldItem = null;
    }

    void EnableColliders(GameObject obj)
    {
        // Przywracanie collider雕 obiektu
        Collider[] colliders = obj.GetComponentsInChildren<Collider>();
        foreach (Collider collider in colliders)
        {
            collider.enabled = true;
        }
    }

    void DisableColliders(GameObject obj)
    {
        // Wy씿czanie collider雕 obiektu
        Collider[] colliders = obj.GetComponentsInChildren<Collider>();
        foreach (Collider collider in colliders)
        {
            collider.enabled = false;
        }
    }

    void MoveObjectToScene(GameObject obj)
    {
        Scene startScene = SceneManager.GetSceneByName("SceneStart");
        if (startScene.isLoaded)
        {
            SceneManager.MoveGameObjectToScene(obj, startScene);
        }
        else
        {
            SceneManager.MoveGameObjectToScene(obj, SceneManager.GetSceneAt(SceneManager.sceneCount - 1));
        }
    }
}